const cors = {
  'Access-Control-Allow-Origin': '',
  'Access-Control-Allow-Credentials': 'true',
  'Access-Control-Allow-Methods': 'GET, PUT, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
};
const OWNER_ID = '1334272703347294210';
const PERMS = ['view_books','create_books','edit_books','delete_books','manage_departments','manage_users','manage_settings'];
function json(body,status=200,origin=''){ return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'true'}}); }
function redirect(url){ return new Response(null,{status:302,headers:{Location:url}}); }
function cookie(request,name){ return (request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||null; }
async function discord(path,env,opts={}){ const r=await fetch('https://discord.com/api/v10'+path,{...opts,headers:{Authorization:`Bot ${env.DISCORD_BOT_TOKEN}`,...(opts.headers||{})}}); return r; }
async function userFromSession(request,env){ const token=cookie(request,'pmb_session'); if(!token)return null; const row=await env.DB.prepare('SELECT * FROM sessions WHERE token=? AND expires_at>?').bind(token,Math.floor(Date.now()/1000)).first(); return row||null; }
async function permissions(request,env,user){ if(!user)return []; if(user.discord_id===OWNER_ID)return PERMS; const rows=await env.DB.prepare('SELECT permission FROM role_permissions rp JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.discord_id=?').bind(user.discord_id).all(); return [...new Set((rows.results||[]).map(x=>x.permission))]; }
function allowed(perms,p){return perms.includes(p);}
export default {async fetch(request,env){
 const origin=new URL(request.url).origin, url=new URL(request.url); if(request.method==='OPTIONS')return new Response(null,{headers:{...cors,'Access-Control-Allow-Origin':origin}});
 if(url.pathname==='/api/auth/login') return redirect(`https://discord.com/oauth2/authorize?client_id=${env.DISCORD_CLIENT_ID}&response_type=code&redirect_uri=${encodeURIComponent(env.DISCORD_REDIRECT_URI)}&scope=identify%20guilds`);
 if(url.pathname==='/api/auth/callback'){const code=url.searchParams.get('code'); if(!code)return redirect('/?login=failed'); const tokenRes=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:env.DISCORD_REDIRECT_URI})}); const tok=await tokenRes.json(); if(!tok.access_token)return redirect('/?login=failed'); const ur=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${tok.access_token}`}}); const du=await ur.json(); const now=Math.floor(Date.now()/1000), session=crypto.randomUUID(); await env.DB.prepare('INSERT INTO users(discord_id,username,avatar,updated_at) VALUES(?,?,?,?) ON CONFLICT(discord_id) DO UPDATE SET username=excluded.username,avatar=excluded.avatar,updated_at=excluded.updated_at').bind(du.id,du.username,du.avatar||'',now).run(); await env.DB.prepare('INSERT INTO sessions(token,discord_id,expires_at) VALUES(?,?,?)').bind(session,du.id,now+604800).run(); return new Response(null,{status:302,headers:{Location:'/', 'Set-Cookie':`pmb_session=${session}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}}); }
 if(url.pathname==='/api/auth/logout')return new Response(null,{status:302,headers:{Location:'/', 'Set-Cookie':'pmb_session=; Path=/; Max-Age=0'}});
 if(url.pathname.startsWith('/api/')){const user=await userFromSession(request,env); if(url.pathname==='/api/me'){return json({loggedIn:!!user,user:user?{discord_id:user.discord_id,username:user.username,avatar:user.avatar}:null,permissions:await permissions(request,env,user)},200,origin)} if(!user)return json({error:'Login required'},401,origin); const perms=await permissions(request,env,user);
  if(url.pathname==='/api/data'){if(request.method==='GET'){if(!allowed(perms,'view_books'))return json({error:'No permission'},403,origin);const row=await env.DB.prepare('SELECT data FROM portal_data WHERE id=1').first();return json(row?JSON.parse(row.data):{departments:[],books:[]},200,origin)} if(request.method==='PUT'){if(!allowed(perms,'edit_books'))return json({error:'No permission'},403,origin);const p=await request.json();await env.DB.prepare('INSERT INTO portal_data(id,data,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(JSON.stringify(p),Math.floor(Date.now()/1000)).run();return json({ok:true},200,origin)}}
  if(url.pathname==='/api/roles'&&request.method==='GET'){if(!allowed(perms,'manage_users'))return json({error:'No permission'},403,origin);const r=await env.DB.prepare('SELECT * FROM role_permissions ORDER BY role_id').all();return json(r.results||[],200,origin)}
  if(url.pathname==='/api/roles'&&request.method==='PUT'){if(!allowed(perms,'manage_users'))return json({error:'No permission'},403,origin);const p=await request.json();await env.DB.prepare('DELETE FROM role_permissions WHERE role_id=?').bind(p.role_id).run();for(const x of p.permissions||[])if(PERMS.includes(x))await env.DB.prepare('INSERT INTO role_permissions(role_id,permission) VALUES(?,?)').bind(p.role_id,x).run();return json({ok:true},200,origin)}
  return json({error:'Not found'},404,origin); }
 return env.ASSETS.fetch(request);
}};
